name: Deploy Windows Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:        # 允许手动触发

jobs:
  windows:
    runs-on: [ self-hosted, linux ]   # 确保这台机器支持 KVM + Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 可选：检查 KVM 是否就绪
      - name: Check KVM
        run: |
          ls -al /dev/kvm
          kvm-ok || true

      # 确保 compose 文件存在
      - name: Validate compose file
        run: docker compose -f a.yml config --quiet

      # 拉取（或构建）镜像
      - name: Pull images
        run: docker compose -f a.yml pull

      # 启动或更新服务
      - name: Deploy / update service
        run: docker compose -f a.yml up -d --remove-orphans

      # 等待健康检查（可选）
      - name: Wait for healthy
        run: |
          for i in {1..30}; do
            state=$(docker inspect --format='{{.State.Health.Status}}' windows 2>/dev/null || true)
            [ "$state" = "healthy" ] && echo "Container healthy" && exit 0
            echo "Waiting for healthy... ($i/30)"
            sleep 10
          done
          echo "::error::Container did not become healthy"
          exit 1
